---
- name: “Apache installation using docker”
  hosts: client1:client2
  become: true
  vars:
    #ansible_sudo_pass: ansadmin retirons le credential pour definir de facon plus securisé
  pre_tasks:
    - name: Install EPEL repo
      package: name= '{{ item }}' state=present
     # when: ansible_distribution == “CentOS”
      loop:
        - epel-release
        - wget
        - git


    - name: download pip script
      get_url:
         url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
         dest: /tmp/get-pip.py

    - name: install python-pip
      command: python2.7 /tmp/get-pip.py
      
    - name: Install docker python
      pip: name=docker-py

  tasks:

    - name: "Copying files to client"
      template:
        src: "index.html.j2"
        dest: "/home/ansadmin/index.html"
     # notify: restart_apache.
 # handlers:
   # - name: restart_apache
     # service:
       # name: httpd
       # state: restarted
       
    
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/ansadmin/index.html/:/usr/local/apache2/htdocs/index.html
