---
- name: remove apache
  hosts: client1:client2
  become: true

  tasks:
     - name: remove nginx container
       docker_container:
         image: httpd
         name: webapp
         state: absent
  
